# Generated by Django 5.2.5 on 2025-08-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
    ]
